---
name: ci
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
jobs:
  yamllint:
    uses: NikitaSkrynnik/.github/.github/workflows/yamllint.yaml@main
    with:
      config_file: "./.yamllint.yml"
