---
name: Update deployments-k8s repository
on:
  push:
    branches:
      - main
  workflow_run:
    types:
      - completed
    workflows:
      - 'automerge'
jobs:
  update-deployments-k8s:
    if: ${{ github.repository != 'networkservicemesh/cmd-template' && (github.event.workflow_run.conclusion == 'success' && github.actor == 'NikitaSkrynnik' || github.event_name == 'push') }}
    uses: NikitaSkrynnik/.github/.github/workflows/update-deployments.yaml@main
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
